[package]
authors = ["patrick.fernie@gmail.com"]
name = "user_agent"
version = "0.3.1"

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"
idna = "0.1.5"
log = "0.4.6"
publicsuffix = "1.5.2"
reqwest = "0.9.6"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"
time = "0.1.42"
try_from = "0.3.2"
url = "1.7.2"

[dependencies.cookie]
features = ["percent-encode"]
version = "0.11.0"

[dev-dependencies]
env_logger = "0.6.0"
pretty_assertions = "0.5.1"
