[package]
authors = ["patrick.fernie@gmail.com"]
name = "user_agent"
version = "0.1.0"

[dependencies]
cookie = { version = "0.8.1", features = ["percent-encode"] }
derive-error-chain = "0.10.1"
env_logger = "0.4.2"
error-chain = "0.10.0"
idna = "0.1"
log = "0.3"
reqwest = "0.5.2"
serde = "1.0.6"
serde_derive = "1.0.6"
serde_json = "1.0.2"
time = "0.1"
try_from = "0.2"
url = "1.2"
