[package]
authors = ["patrick.fernie@gmail.com"]
name = "user_agent"
version = "0.3.0"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
idna = "0.1.4"
log = "0.4.1"
publicsuffix = "1.4.1"
reqwest = "0.9"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
time = "0.1.39"
try_from = "0.2.2"
url = "1.6.0"

[dependencies.cookie]
features = ["percent-encode"]
version = "0.10.1"

[dev-dependencies]
env_logger = "0.5.2"
pretty_assertions = "0.4.1"
