[package]
name = "user_agent"
version = "0.1.0"
authors = ["patrick.fernie@gmail.com"]

[dependencies]
cookie = "0.5"
env_logger = "0.4.2"
idna = "0.1"
log = "0.3"
reqwest = "0.5.2"
serde = "1.0.6"
serde_json = "1.0.2"
serde_derive = "1.0.6"
try_from = "0.2"
time = "0.1"
url = "1.2"
