[package]
authors = ["patrick.fernie@gmail.com"]
name = "user_agent"
version = "0.5.0"
edition = "2018"

[dependencies]
cookie_store = "0.5.0"
url = "1.7.2"
cookie = "0.11.0"
failure = "0.1.5"

[dev-dependencies]
env_logger = "0.6.0"
pretty_assertions = "0.5.1"
